### PR TITLE
Matrix Decompilation

### PR DESCRIPTION
**Pull request by wsp-mbuckley**
Functionality and front end script for decompiling NoRMS and NoHAM matrices.

- [x] Front end script
- [x] Convert NoRMS matrices into TMS segmented PA matrices
- [x] Convert into TfN segmented PA matrices
- [x] Generate gender split TLDs (p, m, g, soc, ns, ca)? Rail data so this is gonna be hard (RDIS?)
- [x] Update Segment Tier Converted to handle Gender segments too

### CODE REVIEW

**Comment by BenTaylor-TfN** [comment]
Updated segment naming can be found in #934. Handles NaN segments, casting, and user class segments (returns `commute` instead if `uccommute` for the segment part`)

**Comment by wsp-mbuckley** [comment]
@BenTaylor-TfN ready for merging into master

**Comment by BenTaylor-TfN** [comment]
Won't do a proper review as this is mostly a Work In Progress, and a quick adaptation of old code. 
We've looked over the code informally, and it's definitely shaping up in the right direction.
Gonna do a few checks then merge into master

**Review by BenTaylor-TfN — APPROVED** [review]
lgtm

**Pull request merged**
