### PR TITLE
Tidy up config folder

### PR DESCRIPTION
**Pull request by BenTaylor-TfN**
Are these config files for the tempro extractor still used?
I would guess that as they haven't been touched in 2 years then they're safe to delete.

@wsp-mbuckley - you might have an idea too?

### CODE REVIEW

**Comment by chrisbstorey** [comment]
Those files define the geographies that you find in tempro. If they come out it will break the lookup to zones. You could get them from the access databases on the fly.

**Comment by BenTaylor-TfN** [comment]
They're definitely important files, but I'm not sure the code still looks for them here. Looking at the commits they were dumped there on the merge with TMS and not been touched since.

Are these files not stored on I drive now and picked up from there?
Been a while since I've been in tempro code to know

**Review by chrisbstorey — COMMENTED** [review]
Happy to merge if it still runs, I suspect there's a job to find:
* A zone desc to zone number file for TEMPRO (in every NTEM database)
* A NTEM to LAD lookup (will be I://, this should really give you a range of LADs to choose from)
*  Another standalone desc to zone number file, I don't know why there are two (in every NTEM databse, probably from the same source, we probably just saved one)

**Comment by BenTaylor-TfN** [comment]
Managed to find the place these are used - looks like the code is still referring to these files.
Will add a backlog item to solve this

**Pull request closed without merging**
